name: dbproject
description: A new Flutter project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  path_provider: ^1.6.27
  sqflite: ^1.3.2+4
  chopper: ^3.0.3
  built_value: ^6.7.0
  built_collection: ^4.3.2
  flutter_bloc: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.7
  built_value_generator: ^6.7.0
  chopper_generator: ^3.0.0


flutter:
  uses-material-design: true

